import RSS from 'rss-generator';
import { Chapter } from './db.js';
import Bokuyaba from './gofers/bokuyaba.js';
import Yangaru from './gofers/yangaru.js';
import fs from 'fs';
import chalk from 'chalk';

function CrawlError(message = '') {
    this.name = 'CrawlError';
    this.message = message;
}; CrawlError.prototype = Error.prototype;

// Tell gofer to crawl for chapters
async function crawlChapters(gofer) {
	let retries = 3;
	let chapters = [];
	while (chapters.length < 1) {
		console.log(chalk.blue('[GOFR]') + ` ${gofer.manga}: Crawling for chapters... (${retries} retries remaining)`);
		chapters = await gofer.crawl();
		retries -= 1;
		if (retries < 0) {
			throw new CrawlError(`Could not get ${gofer.manga} chapters.`);
		}
	}

	return chapters;
};

// Save chapters to DB (without overwriting older entries)
async function saveChapters(chapters) {
	for (let chapter of chapters) {
		const find = await Chapter.findOne({ where: { manga: chapter.manga, title: chapter.title }});
		if (!find) {
			await Chapter.create(chapter);
		}
	}
};

// Load chapters from DB
async function loadChapters(gofer) {
	return await Chapter.findAll({ where: { manga: gofer.manga },
		order: gofer.order ?? [
			['date', 'DESC'],
			['createdAt', 'DESC'],
			['title', 'DESC'],
		]
	});
};

// Generate and save RSS file
function generateRSS(gofer, chapters) {
	const feed = new RSS({
		title: gofer.manga,
		description: `${gofer.manga} chapters automatically generated by crawling.`,
		site_url: gofer.url,
	});

	for (let i in chapters) {
		let chapter = chapters[i];
		chapter.guid = i;
		delete chapter.manga;

		feed.item(chapter);
	}
	
	return fs.writeFileSync(`./rss/${gofer.manga}.rss`, feed.xml());
};

// Begin
export default () => {
	return new Promise((finish) => {
		const gofers = [Bokuyaba, Yangaru];
		const promises = new Array();
		for(let gofer of gofers) {
			promises.push(new Promise(async (resolve, reject) => {
				let chapters;
				try {
					chapters = await crawlChapters(gofer);
				} catch(e) {
					if (e instanceof CrawlError) {
						console.error(chalk.blue('[GOFR]') + ' ' + chalk.red(e.message));
						reject(e);
					} else {
						throw e;
					}
				}
		
				console.log(chalk.blue('[GOFR]') + ` ${gofer.manga}: Saving retrieved ${chapters.length} chapter(s) to database...`);
				await saveChapters(chapters);
		
				console.log(chalk.blue('[GOFR]') + ` ${gofer.manga}: Loading all saved chapters from database...`);
				chapters = await loadChapters(gofer);
				
				
				console.log(chalk.blue('[GOFR]') + ` ${gofer.manga}: Generating RSS file...`);
				generateRSS(gofer, chapters);
		
				console.log(chalk.blue('[GOFR]') + ` ${gofer.manga}: RSS file created.`);
				resolve();
			}));
		}
		
		Promise.allSettled(promises).then(() => {
			console.log(chalk.blue('[GOFR]') + ' Finished generating all RSS files.');
			finish();
		});
	});
};
